INSERT INTO TABLE_APPT VALUES(1,SYSDATE,SYSDATE,'RAM','RAJ','234678','ORIGINAL',SYSDATE,1001);
INSERT INTO DOCTOR VALUES(1001,'NEHA','JASAL','BONE ADJUSTMENT');
INSERT INTO DOCTOR VALUES(1002,'LATA','SRINIVASAN','CAUGH');
INSERT INTO DOCTOR VALUES(1003,'HARINI','NISHANT','HEAD ACHE');
INSERT INTO PATIENT VALUES(1001,'AARUSH','NISHANT','98654567');
INSERT INTO TABLE_APPT VALUES(1,SYSDATE,SYSDATE,'ORIGINAL',SYSDATE,1001,1001);
INSERT INTO HEALTH_CARD VALUES(1001,SYSDATE,'OHIP');
INSERT INTO HEALTH_CARD VALUES(1002,SYSDATE,'SUNLIFE');
INSERT INTO PATIENT_CARDS VALUES(1001,1002);
SELECT * FROM TABLE_APPT a, doctor b  where a.doctor_name_id = b.id;

update TABLE_APPT  set status = 'ORIGINAL' where id = 1